name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run contact validation test
      run: npx playwright test

    # - name: Run contact POS flow test
    #   run: npx playwright test tests/E2E/TC2_PO_contactPosFlow.spec.ts

    # - name: Run buy products test
    #   run: npx playwright test tests/E2E/TC3_PO_buyProducts.spec.ts
